version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "asynchronous-messaging-workshop"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-llq9tnkhqo7y"
s3_prefix = "asynchronous-messaging-workshop"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
